        gcloud builds submit --config=GCS/cloudbuild.yaml .
         gcloud builds submit --config=big-query/cloudbuild.yaml .
         gcloud builds submit --config=data-transfer/cloudbuild.yaml .     
   
