steps:
   - name: 'gcr.io/cloud-builders/gcloud'
     entrypoint: 'bash'
     args:
       - '-c'
       - |		
         gcloud builds submit --config=GCS/cloudbuild.yaml .
         
   - name: 'gcr.io/cloud-builders/gcloud'
     entrypoint: 'bash'
     args:
       - '-c'
       - |		
         gcloud builds submit --config=big-query/cloudbuild.yaml .
 
   - name: 'gcr.io/cloud-builders/gcloud'
     entrypoint: 'bash'
     args:
       - '-c'
       - |		
         gcloud builds submit --config=data-transfer/cloudbuild.yaml .      
