 steps:
  - id: 'tf init'
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: sh
    args: ["-c","terraform -chdir=GCS init"]

    args: ["-c","terraform -chdir=GCS validate"]   

    args: ["-c","terraform -chdir=GCS plan"] 
 
    args: ["-c","terraform -chdir=GCS apply  -auto-approve "] 
  
